name = "passerelle-oh-api-day"
main = "src/index.js"
compatibility_date = "2026-07-01"

[observability]
enabled = true

[triggers]
crons = ["0 4 * * *"]

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "GALAXY"
id = "48c92c470f0d40b29549bd0ac55caf2d"

[[kv_namespaces]]
binding = "CONAV_SESSIONS"
id = "8ef839c34df047a59cc6bbd9e1416c66"
